### PR TITLE
[NCP-3616] added the error message for violating nearChina

### PR DESCRIPTION
**Pull request by jungho73**

### CODE REVIEW

**Review by chiraags — APPROVED** [review]
Good to merge. 

Have added @Jianghai-Quantil  to review Chinese text based on his comments in NCP-3621

**Comment by Jianghai-Quantil** [comment]
@jungho73 I am not quite sure about how to use Github to collaborate. Please help make the following changes. Thanks. I take the chance to change translations for 2 other keys.

AS-IS:
"edgeHostname.clientRegion.invalid.on.nearChina": "近中国服务器组不能用于中国大陆以外的区域。",
"edgeHostname.confirm.cancel.create.edgeHostname": "是否要退出创建此边缘主机名？",
"edgeHostname.confirm.cancel.edit.edgeHostname": "您是否要放弃此边缘主机名的更新？",

TO-BE:
"edgeHostname.clientRegion.invalid.on.nearChina": "nearChina资源不能用于覆盖中国大陆以外的区域。",
"edgeHostname.confirm.cancel.create.edgeHostname": "是否要退出创建此调度域名？",
"edgeHostname.confirm.cancel.edit.edgeHostname": "您是否要放弃此调度域名？",

**Comment by jungho73** [comment]
It's kind of good way to collaborate like this.
And I rewrote the text for Chinese based on your comment.
Thanks.

**Comment by Jianghai-Quantil** [comment]
@jungho73 Sorry, there is a typo in my previous comment. Please use this Chinese text for the key below 
"edgeHostname.confirm.cancel.edit.edgeHostname": "您是否要放弃更新此调度域名？",

**Pull request merged**
