### PR TITLE
[NCP-3136] Sign up -> Sign Up

### PR DESCRIPTION
**Pull request by hwaeunseo**
Please check this PR.
Thanks.

### CODE REVIEW

**Review by burtonquantil — COMMENTED** [review]
@hwaeunseo  why is ngportal-language.babel modified?

**Comment by hwaeunseo** [comment]
@burtonquantil 

https://github.com/mileweb/ngportal-language/pull/346

It seems that chiraags did not add the babel file.
When I modified it to babeledit, the babel file was applied together.
Shall I exclude the babel file?

**Comment by burtonquantil** [comment]
@hwaeunseo  I thought only the .json files would be modified.
I'm not positive as it seems Junhee has repeatedly updated the ngportal-language.babel.
@jungho73  @chiraags  any comment on this?

**Comment by junheeahn** [comment]
@burtonquantil
When you add a new text with BabelEdit, the babel file is modified.
It is not applicable if you just modify the existing text.
In this case, a new Text was added from 0c3462a532b622fa18a40433fd5265f0f5d4722a and 87313a346394d3cc24f718f177b6e23b8c2dbf18 by @chiraags .
However, the babel file has not been modified.
This can happen if you modify the json file immediately without using BabelEdit.
This time, @hwaeunseo's PR was changed because the newly added text by @chiraags was reflected.
Also, among the commits I've worked on so far, the reason why there were many changes to the babel file is that there were many new text additions. I ask for your understanding on this point.
Please give me feedback if there is anything I am mistaken about.
Thank you.

**Comment by burtonquantil** [comment]
@junheeahn  OK if it is expected. You can approve her pull request so she can merge it.

**Review by junheeahn — APPROVED** [review]
OK to merge.

**Comment by AlexQuantil** [comment]
@hwaeunseo @junheeahn What version of BabelEdit are you using?
I'm using BabelEdit 2.7.1 with the serial number purchased by Bin. But I can't open the .babel project file in this repo.
image

**Comment by junheeahn** [comment]
@AlexQuantil I and @hwaeunseo are using BabelEdit 2.8.0 with the serial number purchased by Bin.

**Comment by junheeahn** [comment]
@AlexQuantil And, for your information, it is assumed that the 2.8.0 version has also been used by Lizhi Guo.
Please refer to the screenshot below.
image
Thanks.

**Comment by chiraags** [comment]
image

As seen in the screenshot (notice the date modified), the babel file was not updated when I added the new texts (on 21 October, 2022). Git too didn't prompt me to add the babel file.

I use BabelEdit 2.7.0.

If the absence of the BabelEdit file is causing inconsistencies, I will include that in future pull requests.

**Pull request merged**
